description: |
  The footer is created with a simple design that is meant to match the style of the business through simplicity and colour.

  The footer can be combined with navigation, icons, and colour.
