description: |
  The buttons chosen for this website have a focus on the minimalist and round style that is incorporated throughout the branding.

  Buttons can be combined with cards, banners, and forms.


patterns:
  button:
    title: "Main Button"
    description: |
      Main button used throughout the web app.
    background: "--color-secondary-light-blue"
    fields:
      - name: text
        type: string
        example: "Donate"
      - name: color
        type: string
        example: "btn-orange"
      - name: link
        type: string
        example: "#"
  special-button:
    title: "Special Button"
    description: |
      The button used for the donation form.
    background: "--color-accent-purple"
