description: |
  The header is created with a simple design that is meant to match the style of the business through simplicity and colour.

  The header can be combined with navigation, icons, images, and animation.

patterns:
  header:
    title: "Header"
    description: |
      This is a simple header that will be placed on top of the main banner using a background transperancy. This is also part of the default layout.
    background: "--color-secondary-light-blue"
    fields:
      - name: text
        type: string
        example: "Bushfires"
      - name: link
        type: string
        example: "#"
  navigation:
    title: "Navigation"
    description: |
      This is a simple navigation that will be added to the main header. It contains the dropdown menu content.
    background: "--color-accent-orange-dark"