description: |
  The sections are to be used throughout the website in areas with large amounts of content where there are multiple elements present.

  Sections are combined with text, images, buttons, cards, and navigation.

patterns:
  multiple-cards:
    title: "Multiple Cards Section"
    description: |
      Used to list multiple cards on one page.
