description: |
  The cards section is to be used where there is need for a call-to-action to include a card that will link to a project page.

  Cards can be combined with buttons, and be placed in banners and sections.

patterns:
  info-card:
    title: "Info Card"
    description: |
      Info card can be used to describe each cause and directs the user to the organizations pages for each.
    fields:
      - name: title
        type: string
        example: "Bush Fires"
      - name: description
        type: string
        example: "Bushfires are very common throughout Australia. They impact extensive areas and have killed over 800 people and millions of animals."
      - name: icon
        type: string
        example: "humanaid-icon"
