description: |
  This will be the standard banner that will always appear at the top of the page. The navigation/header will be placed (via patterns) ontop of this (transparently).

  Banners can be combined with buttons.
